### ISSUE TITLE
npm install doesn't work on Windows 10

### ISSUE THREAD

**Issue by Suhail** [master-atul/blog-addons-example#3]
I know this is a strange request but I tried to get this working on Windows & it had a strange error. I am not sure why it can't find the file since it seems like one part of it can find the files. I am asking because I am trying to make a node add-on that will work on Windows.

```
PS C:\Users\digit\Desktop\blog-addons-example> npm install

> test-addon@1.0.0 install C:\Users\digit\Desktop\blog-addons-example
> node-gyp rebuild


C:\Users\digit\Desktop\blog-addons-example>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  win_delay_load_hook.cc
  Generating code
  All 1 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  nothing.vcxproj -> C:\Users\digit\Desktop\blog-addons-example\build\Release\\nothing.node
  main.cpp
  functionexample.cpp
  actualclass.cpp
  classexample.cpp
  win_delay_load_hook.cc
c1xx : fatal error C1083: Cannot open source file: '..\cppsrc\Samples\functionexample.cpp': No such file or directory [
C:\Users\digit\Desktop\blog-addons-example\build\testaddon.vcxproj]
c1xx : fatal error C1083: Cannot open source file: '..\cppsrc\Samples\actualclass.cpp': No such file or directory [C:\U
sers\digit\Desktop\blog-addons-example\build\testaddon.vcxproj]
c1xx : fatal error C1083: Cannot open source file: '..\cppsrc\Samples\classexample.cpp': No such file or directory [C:\
Users\digit\Desktop\blog-addons-example\build\testaddon.vcxproj]
c:\users\digit\desktop\blog-addons-example\cppsrc\main.cpp(2): fatal error C1083: Cannot open include file: 'Samples/fu
nctionexample.h': No such file or directory [C:\Users\digit\Desktop\blog-addons-example\build\testaddon.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\digit\Desktop\blog-addons-example
gyp ERR! node -v v11.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-addon@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test-addon@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\digit\AppData\Roaming\npm-cache\_logs\2019-03-13T22_31_58_463Z-debug.log
```

npm --version: 6.7.0
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.17134 N/A Build 17134

--

Running this from Ubuntu works just fine!

**Comment by Suhail** [comment]
Good news is I can get it all to run if I place everything in main.cpp though.

**Comment by a7ul** [comment]
Hey @Suhail Sorry for not replying I completely missed this one. I hope you were able to fix it. Closing this for now.
